# Generated by Django 4.2.2 on 2023-11-09 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsApp', models.CharField(max_length=12, null=True, unique=True)),
                ('addresse', models.CharField(max_length=200, null=True)),
                ('technologie', models.CharField(choices=[('Web Developer', 'Web Developer'), ('Mobile App Developer', 'Mobile App Developer'), ('Graphic Designer', 'Graphic Designer'), ('Content Writer', 'Content Writer'), ('Social Media Manager', 'Social Media Manager'), ('Virtual Assistant', 'Virtual Assistant'), ('Data Analyst', 'Data Analyst'), ('SEO Specialist', 'SEO Specialist'), ('Project Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('iOS Developer', 'iOS Developer'), ('PHP Developer', 'PHP Developer'), ('Email Marketer', 'Email Marketer'), ('Paid Media Experts', 'Paid Media Expert'), ('E-commerce Developer', 'E-commerce Developer')], max_length=50, null=True)),
                ('lien_facebook', models.CharField(max_length=50, null=True, unique=True)),
                ('lien_github', models.CharField(max_length=20, null=True, unique=True)),
                ('discord', models.CharField(max_length=50, null=True, unique=True)),
                ('upwork', models.CharField(max_length=100, null=True)),
                ('apropos', models.TextField(null=True)),
                ('photo', models.ImageField(default='avatar.jpg', upload_to='Profile_Images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
